version: '3'
services:
  frontend:
    image: frontend
    ports: 
      - ${FRONTEND_PORT}:8080
    volumes:
      - ./frontend:/usr/src/app
  api:
    image: api
    ports:
      - "${FLASK_PORT}:5000"
    expose:
      - "${FLASK_PORT}"
    volumes:
      - ./api/app.py:/app/app.py
      - ./api/mongo_url.py:/app/mongo_url.py
  nginx:
    image: nginx
    ports:
      - 8085:80
    depends_on:
      - api
  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./mongodb-storage:/data/db
    command: [--auth]
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      ports:
        - 3307:3306
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8090:8080
        - 8443:8443
      depends_on:
        - mysql
#  cypress:
#    image: cypress/included:3.2.0
#    volumes: 
#      - ./cypress_volume:/cypress
#      - ./cypress_volume/cypress.json:/cypress.json

volumes:
  mysql_data:
      driver: local
