version: '3'
services:
  frontend:
    image: frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
  api:
    image: api
    ports:
      - "${FLASK_PORT}:5000"
    expose:
      - "${FLASK_PORT}"
  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./mongodb-storage:/data/db
