version: '3'
services:
  frontend:
    image: frontend
    ports:
      - "${FRONTEND_PORT}:8080" 
    volumes:
      - ./frontend/public:/usr/src/app/public
  api:
    image: api
    ports:
      - "${FLASK_PORT}:5000"
    expose:
      - "${FLASK_PORT}"
    volumes:
      - ./api/app.py:/app/app.py
      - ./api/mongo_url.py:/app/mongo_url.py
  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./mongodb-storage:/data/db
    command: [--auth]
#  cypress:
#    image: cypress/included:3.2.0
#    volumes: 
#      - ./cypress_volume:/cypress
#      - ./cypress_volume/cypress.json:/cypress.json
