version: '3'
services:
  frontend:
    image: frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
  api:
    ports:
      - "5001:5000"
    expose:
      - "5001"
    image: api
  mongodb:
    image: mongo
      ports:
        - "27018:27017"
    volumes:
      - ./mongodb-storage:/data/db
