version: '3'
services:
  frontend:
    image: frontend
    ports:
      - "${FRONTEND_PORT}:8080"
      - "8085:8081"
    volumes:
      - ./frontend/public:/usr/src/app/public
  api:
    image: api
    ports:
      - "${FLASK_PORT}:5000"
    expose:
      - "${FLASK_PORT}"
  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./mongodb-storage:/data/db
  cypress:
    image: cypress/included:3.2.0
    volumes: 
      - ./cypress_volume:/cypress
      - ./cypress_volume/cypress.json:/cypress.json
